# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

FROM quay.io/hummingbird/python:3.13
COPY server.py /app/server.py
EXPOSE 8080
CMD ["python", "/app/server.py"]
